channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - cython
    - pillow
    - numpy
    - opencv-python
    - torch --extra-index-url https://download.pytorch.org/whl/cpu
    - torchvision --extra-index-url https://download.pytorch.org/whl/cpu
    - pytest==8.2.2
    - tqdm==4.64.1
    - scipy
    - matplotlib
    - mock==4.0.3
    - imageai